# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_artical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='answerCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artical',
            name='best_answer_no',
            field=models.IntegerField(default=0),
        ),
    ]
