# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170615_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
